# netlify.toml
# Configuration file for Netlify deployment

[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Configure serverless functions
  node_bundler = "esbuild"
  # Include necessary files
  included_files = ["prisma/**", "src/lib/**", "node_modules/.prisma/**", "node_modules/@prisma/**"]
  # External modules that shouldn't be bundled
  external_node_modules = ["@prisma/client", ".prisma/client", "bcryptjs", "next-auth"]
